version: '3.8'
services:
    # db:
    #     container_name: postgres_container
    #     image: postgres:14.2
    #     restart: always
    #     environment:
    #         POSTGRES_USER: ${POSTGRES_USER}
    #         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #         POSTGRES_DB: ${POSTGRES_DB}
    #     ports:
    #         - 5432:5432
    # pgadmin:
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4:6.8
    #     restart: always
    #     depends_on:
    #         - db
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #     ports:
    #         - 5050:80
    api:
        container_name: "api"
        environment:
            - NODE_ENV:${NODE_ENV}
        build:
            context: ./
            dockerfile: ./docker/api/Dockerfile
        entrypoint: ["npm", "run", "start:prod"]
        user: node
        env_file:
            - .env
        ports:
            - 3000:3000
        # networks:
        #     - pjuh-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

# networks:
#     pjuh-network:
